### ISSUE TITLE
Custom ModuleTemplate should enabled with remoteModuleTemplateRef

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/kyma-dashboard#219]
**Description**
At the moment, Kyam dashboard support to show customized ModuleTemplate which user uploaded, but after enable it within the UI, the spec field was wrong, customized ModuleTemplate can't treat same as KCP moduleTemplate. LM expected  `remoteModuleTemplateRef` which referenced those module to distinguish with KCP ones.

**Expected result**

in Kyma CR, it should contain `remoteModuleTemplateRef` with FQDN of the module for customized ModuleTemplate.
```
module:
    - channel: regular
      customResourcePolicy: CreateAndDelete
      remoteModuleTemplateRef: kyma-project.io/elastic-search
      name: elastic-search
```

**Actual result**

```
    - channel: regular
      customResourcePolicy: CreateAndDelete
      name: elastic-search
```

**Steps to reproduce**

Submit a customized ModuleTemplate to staging btp cluster, you can use this one [template-elastic-search.yaml.zip](https://github.com/kyma-project/kyma-dashboard/files/12369750/template-elastic-search.yaml.zip), enable it with Kyma Dashboard, it shows error for this module.

**Troubleshooting**
