### ISSUE TITLE
dynamicValue in the Busola extension doesn't really work

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma-dashboard#51]
**Description**

Kyma Subscription's sink contains the so-called sink, which is a k8s Service. The **expected logic** is as follows:
1. User selects a service from the dropdown:
<img width="651" alt="image" src="https://user-images.githubusercontent.com/15933100/209328424-c19bcec8-476f-4b17-a17b-72477d5c58a1.png">

2. Once the service is selected, the same input is being manipulated as follows:
` '"http://" & $service & "." & $root.metadata.namespace & ".svc.cluster.local"'`

Currently, this is **not possible.** You can only do this with two fields by using `subscribe` and `trigger` like that:
```
   - simple: true
      type: string
      var: service
      name: Service
      widget: Resource
      resource:
        kind: Service
        version: v1
        scope: namespace
      trigger: [sink]
    - path: spec.sink
      name: spec.sink
      simple: true
      inputInfo: inputInfo.sink
      placeholder: placeholder.sink
      subscribe:
        sink: '"http://" & $service & "." & $root.metadata.namespace & ".svc.cluster.local"'
```
Would it be possible to have this logic within one field ?

I tried with dynamicValue like this:
```
   - path: spec.sink
      name: spec.sink
      var: sink
      simple: true
      inputInfo: inputInfo.sink
      placeholder: placeholder.sink
      dynamicValue: '"http://" & $sink & "." & $root.metadata.namespace & ".svc.cluster.local"'
```

but it doesn't recognise the `$sink` value and prints it out as empty, so in the end I get `http://.namespace.svc.cluster.local` instead of `http://${sinkValue}.namespace.svc.cluster.local`

**Comment by qbalukom** [comment]
Hi. `dynamicValue` is not mean to be changed on user input - this only sets the default value of a variable dynamically based on source data (so only on form load and when switching back from the "yaml" tab).

However triggers and subscriptions can be placed on the same field. As such this should work as a single field solution:
```
- path: spec.sink
  name: spec.sink
  widget: Resource
  resource:
    kind: Service
    version: v1
    scope: namespace
  simple: true
  inputInfo: inputInfo.sink
  placeholder: placeholder.sink
  trigger: [sink]
  subscribe:
    sink: '"http://" & spec.sink & "." & $root.metadata.namespace & ".svc.cluster.local"'
```
