### ISSUE TITLE
Cannot type into the SimpleList input in the simple mode, while it works in the advanced mode

### ISSUE THREAD

**Issue by VladislavPaskar** [kyma-project/kyma-dashboard#65]
**Description**

This [PR](https://github.com/kyma-project/kyma/pull/16381) introduced new UI for Subscriptions tab. There is a `SimpleList` defined as follows:
```
   - path: spec.types
      simple: true
      widget: SimpleList
      defaultExpanded: true
      children:
        - path: '[]'
```

Currently, in the prod Dashboard one cannot type anything in this input in the simple mode. Typing in the advanced mode works as expected.

**Comment by mrCherry97** [comment]
Hi @VladislavPaskar 
In this case `SimpleList` should be defined like this:
```
   - path: spec.types
      simple: true
      widget: SimpleList
      defaultExpanded: true
      children:
        - path: '[]'
           simple: true
```
Please check it and if problem appears please reopen the issue.
