### ISSUE TITLE
Description is not working for object CRD fields in the extensions

### ISSUE THREAD

**Issue by vpaskar** [kyma-project/kyma-dashboard#71]
**Description**

We have a following object CRD field:
```
config:
    additionalProperties:
      type: string
    description: Config defines the configurations that can be applied
      to the eventing backend
    type: object
```

the description is not being rendered as expected:
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/15933100/211804453-2d253ea0-e552-4bbf-a31a-4e4e5b10f32b.png">

for usual fields the description is working:
```
typeMatching:
      description: TypeMatching defines the type of matching to be done
        for the event types
      type: string
```
is rendered as:
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/15933100/211804633-41b46acb-8994-4e8f-829f-f22f13dc5c43.png">
